# Generated by Django 2.2.6 on 2020-02-15 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200212_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_photo',
            name='upload_post',
            field=models.FileField(blank=True, upload_to='post/%y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='bio',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='phone',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
