# Generated by Django 2.2.6 on 2020-02-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200215_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_photo',
            name='upload_post',
            field=models.ImageField(blank=True, upload_to='post/%y/%m/%d/'),
        ),
    ]
