# Generated by Django 2.2.6 on 2020-02-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200215_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_photo',
            name='upload_post',
            field=models.FileField(blank=True, upload_to='post/%y/%m/%d/'),
        ),
    ]
