# Generated by Django 2.2.6 on 2020-02-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20200228_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_photo',
            name='upload_post',
            field=models.FileField(blank=True, upload_to='{user.username}post/%y/%m/%d/'),
        ),
    ]
