# Generated by Django 2.2.6 on 2020-02-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20200228_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_photo',
            name='upload_post',
            field=models.FileField(blank=True, upload_to='{{User.username}}post/%y/%m/%d/'),
        ),
    ]
