# Generated by Django 2.2.6 on 2020-02-29 04:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20200228_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_photo',
            name='post_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
