# Generated by Django 2.2.6 on 2020-02-29 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_profile_photo_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_photo',
            name='upload_post',
            field=models.FileField(blank=True, null=True, upload_to='post/%y/%m/%d/'),
        ),
    ]
