# Generated by Django 2.2.6 on 2020-03-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20200324_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='upload_post',
            field=models.ImageField(blank=True, null=True, upload_to='post_by_users/%y/%m/%d/'),
        ),
    ]
