# Generated by Django 2.2.6 on 2020-03-24 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20200324_1548'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
