# Generated by Django 2.2.6 on 2020-03-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_photo',
            name='upload_post',
            field=models.ImageField(blank=True, null=True, upload_to='post/%y/%m/%d/'),
        ),
    ]
