# Generated by Django 2.2.6 on 2020-03-29 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
